# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

dist: trusty
language: r
sudo: required
r_binary_packages:
  - stringr
  - devtools
apt_packages:
  - octave 
  - liboctave-dev
  - biblatex
cache: packages
r: bioc-release
warnings_are_errors: false
